{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Api --> Banco Entre Ríos",
    "description" : "BFF para la web del Banco Entre Rios.  ",
    "contact" : {
      "name" : "banco entre rios",
      "url" : "https://www.bancoentrerios.com.ar/acaparacreditos/#",
      "email" : "roy.cuenca@naturalth.it"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "http://localhost:3000/v1/ber",
    "description" : "Datos formulario (GET)"
  } ],
  "paths" : {
    "/pymes/credits" : {
      "get" : {
        "tags" : [ "API - Endpoints" ],
        "description" : "Endpoint Permite obtener un objeto json con los datos para los formularios. Solo ejecutar la Request y se obtendra el objeto json.",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "Content" : {
                "schema" : {
                  "type" : "object",
                  "description" : "Datos Formulario",
                  "example" : {
                    "error" : false,
                    "message" : "OK",
                    "status" : 200,
                    "data" : [ {
                      "proveedorTelefonoMovil" : [ {
                        "value" : "cti",
                        "label" : "Claro"
                      }, {
                        "value" : "movistar",
                        "label" : "Movistar"
                      }, {
                        "value" : "nextel",
                        "label" : "Nextel"
                      }, {
                        "value" : "personal",
                        "label" : "Personal"
                      } ],
                      "provincia" : [ {
                        "value" : "1",
                        "label" : "Capital Federal"
                      }, {
                        "value" : "2",
                        "label" : "Buenos Aires"
                      }, {
                        "value" : "3",
                        "label" : "CATAMARCA"
                      }, {
                        "value" : "4",
                        "label" : "CORDOBA"
                      }, {
                        "value" : "5",
                        "label" : "CORRIENTES"
                      }, {
                        "value" : "6",
                        "label" : "CHACO"
                      }, {
                        "value" : "7",
                        "label" : "CHUBUT"
                      }, {
                        "value" : "8",
                        "label" : "ENTRE RIOS"
                      }, {
                        "value" : "9",
                        "label" : "FARMOSA"
                      }, {
                        "value" : "10",
                        "label" : "JUJUY"
                      }, {
                        "value" : "11",
                        "label" : "LA PAMPA"
                      }, {
                        "value" : "12",
                        "label" : "LA RIOJA"
                      }, {
                        "value" : "13",
                        "label" : "MENDOZA"
                      }, {
                        "value" : "14",
                        "label" : "MISIONES"
                      }, {
                        "value" : "15",
                        "label" : "NEUQUEN"
                      }, {
                        "value" : "16",
                        "label" : "RIO NEGRO"
                      }, {
                        "value" : "17",
                        "label" : "SALTA"
                      }, {
                        "value" : "18",
                        "label" : "SAN JUAN"
                      }, {
                        "value" : "19",
                        "label" : "SAN LUIS"
                      }, {
                        "value" : "20",
                        "label" : "SANTA CRUZ"
                      }, {
                        "value" : "21",
                        "label" : "SANTA FE"
                      }, {
                        "value" : "22",
                        "label" : "SANTIAGO DEL ESTERO"
                      }, {
                        "value" : "23",
                        "label" : "TUCUMAN"
                      }, {
                        "value" : "24",
                        "label" : "TIERRA DEL FUEGO, ANTARTUDA E ISLAS"
                      } ],
                      "clienteBancario" : [ {
                        "value" : true,
                        "label" : "SI"
                      }, {
                        "value" : false,
                        "label" : "NO"
                      } ],
                      "montoMaximoParaSolicitar" : 10000000,
                      "actividad" : [ {
                        "value" : "2",
                        "label" : "Agropecuario",
                        "destino" : [ {
                          "value" : "13",
                          "label" : "Adquisición de Camiones y Acoplados",
                          "garantia" : [ {
                            "value" : "13",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "14",
                          "label" : "Maquinas Agricolas",
                          "garantia" : [ {
                            "value" : "14",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "15",
                          "label" : "Pick Up y Rodados",
                          "garantia" : [ {
                            "value" : "15",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "16",
                          "label" : "Leasing Rodados",
                          "garantia" : [ {
                            "value" : "16",
                            "label" : "Leasing"
                          } ]
                        }, {
                          "value" : "17",
                          "label" : "Compra y/o Retención de Hacienda (Hasta $1.500.000)",
                          "garantia" : [ {
                            "value" : "17",
                            "label" : "Sola Firma / Fianza"
                          } ]
                        }, {
                          "value" : "18",
                          "label" : "Insumos siembra fina y/o gruesa (Hasta $1.500.000)",
                          "garantia" : [ {
                            "value" : "18",
                            "label" : "Sola Firma / Fianza"
                          } ]
                        }, {
                          "value" : "19",
                          "label" : "Insumos para Tambo (Hasta $1.500.000)",
                          "garantia" : [ {
                            "value" : "19",
                            "label" : "Sola Firma / Fianza"
                          } ]
                        } ]
                      }, {
                        "value" : "3",
                        "label" : "Comercio",
                        "destino" : [ {
                          "value" : "32",
                          "label" : "Adquisición de Camiones y Acoplados",
                          "garantia" : [ {
                            "value" : "32",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "33",
                          "label" : "Utilitarios",
                          "garantia" : [ {
                            "value" : "33",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "34",
                          "label" : "Pick Up y Rodados",
                          "garantia" : [ {
                            "value" : "34",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "35",
                          "label" : "Leasing Rodados",
                          "garantia" : [ {
                            "value" : "35",
                            "label" : "Leasing"
                          } ]
                        }, {
                          "value" : "36",
                          "label" : "Maquinas y Equipos",
                          "garantia" : [ {
                            "value" : "36",
                            "label" : "Hipotecaria"
                          } ]
                        }, {
                          "value" : "37",
                          "label" : "Capital de Trabajo (Hasta $1.500.000)",
                          "garantia" : [ {
                            "value" : "37",
                            "label" : "Sola Firma / Fianza"
                          } ]
                        }, {
                          "value" : "38",
                          "label" : "ICapital de Trabajo (Mayor $1.500.000)",
                          "garantia" : [ {
                            "value" : "38",
                            "label" : "Hipotecaria"
                          } ]
                        } ]
                      }, {
                        "value" : "4",
                        "label" : "Servicios",
                        "destino" : [ {
                          "value" : "47",
                          "label" : "Adquisición de Camiones y Acoplados",
                          "garantia" : [ {
                            "value" : "47",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "48",
                          "label" : "Utilitarios",
                          "garantia" : [ {
                            "value" : "48",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "49",
                          "label" : "Pick Up y Rodados",
                          "garantia" : [ {
                            "value" : "49",
                            "label" : "Prendaria"
                          } ]
                        }, {
                          "value" : "50",
                          "label" : "Leasing Rodados",
                          "garantia" : [ {
                            "value" : "50",
                            "label" : "Leasing"
                          } ]
                        }, {
                          "value" : "51",
                          "label" : "Maquinas y Equipos",
                          "garantia" : [ {
                            "value" : "51",
                            "label" : "Hipotecaria"
                          } ]
                        }, {
                          "value" : "52",
                          "label" : "Maquinas y Equipos Viales",
                          "garantia" : [ {
                            "value" : "52",
                            "label" : "Hipotecaria"
                          } ]
                        }, {
                          "value" : "53",
                          "label" : "Capital de Trabajo (Hasta $1.500.000)",
                          "garantia" : [ {
                            "value" : "53",
                            "label" : "Sola Firma / Fianza"
                          } ]
                        } ]
                      } ]
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/pymes/validateCuit/{cuit}" : {
      "post" : {
        "tags" : [ "API - Endpoints" ],
        "description" : "Endpoint para validar Cuit(pyme) Cuits de prueba - sin cuit - cuit incompleto - \"11111111111\" - \"22222222222\"",
        "parameters" : [ {
          "name" : "cuit",
          "in" : "path",
          "type":"string",
          "description" : "Cuit del cliente",
          "required" : true,
          "example" : "44444444444"
        } ],
        "responses" : {
          "200" : {
            "description" : "Cuit igual a \"33333333333\"",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "description" : "Http status code response 200 mensaje OK",
                  "example" : {
                    "error" : false,
                    "message" : "OK",
                    "status" : 200,
                    "payload" : {
                      "isValid" : true,
                      "isMonotributista" : false
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Cuit menor o mayor a 11 caracteres",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "description" : "Mensaje \"El CUIT es invalido\"",
                  "example" : {
                    "error" : {
                      "message" : "El Cuit es invalido"
                    },
                    "payload" : {
                      "isValid" : false,
                      "isMonotributista" : false
                    }
                  }
                }
              }
            }
          },
          "402" : {
            "description" : "Cuit igual a \"11111111111\"",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "description" : "Mensaje \"CUIT no valido como empresa\"",
                  "example" : {
                    "error" : {
                      "message" : "CUIT no valido como empresa"
                    },
                    "payload" : {
                      "isValid" : false,
                      "isMonotributista" : false
                    }
                  }
                }
              }
            }
          },
          "504" : {
            "description" : "Cuit igual a \"22222222222\"",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "description" : "Mensaje \"Servicio del grupo no disponible\"",
                  "example" : {
                    "error" : {
                      "message" : "Servicio del grupo no disponible"
                    },
                    "payload" : {
                      "isValid" : false,
                      "isMonotributista" : false
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/pymes/validateSignUp" : {
      "post" : {
        "tags" : [ "API - Endpoints" ],
        "description" : "Endpoint para validar la inscripcion(pyme).",
        "parameters" : [ {
          "name" : "Validate sign up request",
          "in" : "body",
          "description" : "Objeto json con todos los datos del formulario.",
          "required" : true,
          "schema" : {
            "$ref" : "#/components/schemas/Validate sign up request"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Cualquier otro caso",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "description" : "Http status code response 200",
                  "example" : {
                    "error" : false,
                    "message" : "OK",
                    "status" : 200,
                    "payload" : {
                      "cuit" : "string",
                      "email" : "string",
                      "proveedorTelefonoMovil" : "string",
                      "telefonoMovil" : "string",
                      "razonSocialNombreApellido" : "string",
                      "fechaDDJJ" : "string",
                      "resultadoNeto" : "string",
                      "nombreApellido" : "string",
                      "actividad" : "string",
                      "valorInmueble" : "string",
                      "destino" : "string",
                      "facturacionAnual" : "string",
                      "garantia" : "string",
                      "montoMaximo" : "string",
                      "montoSolicitado" : 100,
                      "recaptcha" : "string",
                      "monotributista" : "string",
                      "fechaNacimiento" : "string",
                      "codigoPostal" : "string"
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Dato de entrada incorrecto",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "description" : "nombreApellido = \"Pepe Argento\"",
                  "example" : {
                    "error" : {
                      "message" : "Dato de entrada incorrecto"
                    }
                  }
                }
              }
            }
          },
          "504" : {
            "description" : "Servicio del grupo no disponible",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "description" : "nombreApellido = \"Moni Argento\"",
                  "example" : {
                    "error" : {
                      "message" : "Servicio del grupo no disponible"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Validate sign up request" : {
        "type" : "object",
        "properties" : {
          "cuit" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "proveedorTelefonoMovil" : {
            "type" : "string"
          },
          "telefonoMovil" : {
            "type" : "string"
          },
          "razonSocialNombreApellido" : {
            "type" : "string"
          },
          "fechaDDJJ" : {
            "type" : "string"
          },
          "resultadoNeto" : {
            "type" : "string"
          },
          "nombreApellido" : {
            "type" : "string"
          },
          "actividad" : {
            "type" : "string"
          },
          "valorInmueble" : {
            "type" : "string"
          },
          "destino" : {
            "type" : "string"
          },
          "montoMaximo" : {
            "type" : "string"
          },
          "montoSolicitado" : {
            "type" : "number"
          },
          "recaptcha" : {
            "type" : "string"
          },
          "monotributista" : {
            "type" : "string"
          },
          "fechaNacimiento" : {
            "type" : "string"
          },
          "codigoPostal" : {
            "type" : "string"
          }
        },
        "example" : {
          "cuit" : "20957655547",
          "email" : "rodolfo@gmail.com",
          "proveedorTelefonoMovil" : "movistar",
          "telefonoMovil" : "1153746354",
          "razonSocialNombreApellido" : "238273",
          "fechaDDJJ" : "27/05/1989",
          "resultadoNeto" : "8738478",
          "nombreApellido" : "rafael aguirre",
          "actividad" : "actividad",
          "valorInmueble" : "7382783",
          "destino" : "destino",
          "facturacionAnual" : "273837823",
          "garantia" : "28372837",
          "montoMaximo" : "8237837763",
          "montoSolicitado" : 15000000,
          "recaptcha" : "string",
          "monotributista" : "string",
          "fechaNacimiento" : "03/03/1987",
          "codigoPostal" : "1426"
        }
      }
    }
  }
}